#!/bin/sh

# Set correct bin path if we are running as a cron job
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

bin_dir=`dirname $0`
programm="$bin_dir/homer_pgsql_rotate.pl"
config="$bin_dir/rotation.ini"

$programm $config

