#!/bin/bash
# HOMER 5.x Install/Uninstall Helper
# v0.1 04/11/2015 (C) SIPCAPTURE.ORG

if [ "$1" == "install" ]; then
        echo "Installing Homer configuration..."
elif [ "$1" == "uninstall" ]; then
        echo "Uninstalling Homer configuration..."
else
        echo "Invalid params! Skipping Homer configuration..."
fi

